### ISSUE TITLE
Error while dispatching event for sensor.epex_spot_data_net_price

### ISSUE THREAD

**Issue by heinemannj** [mampfes/ha_epex_spot_sensor#6]
Logger: homeassistant.helpers.event
Source: helpers/event.py:296
First occurred: 13:54:32 (1 occurrences)
Last logged: 13:54:32

Error while dispatching event for sensor.epex_spot_data_net_price to <Job track state_changed event ['sensor.epex_spot_data_net_price'] HassJobType.Callback <function BinarySensor.__init__.<locals>.async_price_sensor_state_listener at 0x7f79aaaca0>>
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/helpers/event.py", line 296, in _async_dispatch_entity_id_event
    hass.async_run_hass_job(job, event)
  File "/usr/src/homeassistant/homeassistant/core.py", line 691, in async_run_hass_job
    hassjob.target(*args)
  File "/config/custom_components/epex_spot_sensor/binary_sensor.py", line 174, in async_price_sensor_state_listener
    _on_price_sensor_state_update()
  File "/config/custom_components/epex_spot_sensor/binary_sensor.py", line 167, in _on_price_sensor_state_update
    self._update_state()
  File "/config/custom_components/epex_spot_sensor/binary_sensor.py", line 241, in _update_state
    self._update_state_for_contigous(earliest_start, latest_end, now)
  File "/config/custom_components/epex_spot_sensor/binary_sensor.py", line 294, in _update_state_for_contigous
    marketdata = get_marketdata_from_sensor_attrs(self._sensor_attributes)
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/config/custom_components/epex_spot_sensor/util.py", line 51, in get_marketdata_from_sensor_attrs
    return [Marketprice(e) for e in data]
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/config/custom_components/epex_spot_sensor/util.py", line 51, in <listcomp>
    return [Marketprice(e) for e in data]
            ^^^^^^^^^^^^^^
  File "/config/custom_components/epex_spot_sensor/util.py", line 21, in __init__
    raise KeyError()
KeyError

**Comment by mampfes** [comment]
Which EPEX Spot data source (Awattar, EPEX Spot Web Scraper, ...) and which market area are you using?

**Comment by mampfes** [comment]
This error will be raised if you select an invalid price sensor. This you select "Price" or "Net Price" sensor?

**Comment by heinemannj** [comment]
I think so ...
I have deinstalled, but I can reinstall with a good instruction ...

**Comment by mampfes** [comment]
What do you mean with "good instruction"? Do you need extra help?
